import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faReacteurope,
} from '@fortawesome/free-brands-svg-icons';
import {
  faFolderOpen,
} from '@fortawesome/free-regular-svg-icons';
import {
  faTools,
  faDesktop,
  faLayerGroup,
  faCheck,
  faFileImport,
  faFileExcel,
  faPlusCircle,
  faPlug,
  faUnlink,
  faExclamationTriangle,
  faCogs,
  faAlignJustify,
  faTh,
  faBoxes,
  faSitemap,
  faStream,
  faAngleDown,
  faUser,
  faEnvelope,
  faLock,
  faKey,
  faBan,
} from '@fortawesome/free-solid-svg-icons';

library.add(
  faTools,
  faDesktop,
  faLayerGroup,
  faCheck,
  faFileImport,
  faFileExcel,
  faPlusCircle,
  faPlug,
  faUnlink,
  faExclamationTriangle,
  faCogs,
  faAlignJustify,
  faTh,
  faBoxes,
  faSitemap,
  faStream,
  faAngleDown,
  faFolderOpen,
  faReacteurope,
  faUser,
  faEnvelope,
  faLock,
  faKey,
  faBan,
);
